### ISSUE TITLE
SQLite failure on patch participant team_id=nil

### ISSUE THREAD

**Issue by compnerd** [AgaKhanFoundation/WCB#94]
<- [PATCH] http://akf-causes.subshell.org/participants/103271954406957
-> [400] {"error":{"code":400,"message":"SQLITE_ERROR: near \"WHERE\": syntax error"}}

The request was setting `team_id` to nil to leave the team.

**Comment by compnerd** [comment]
utils/client.py participant u <fbid> team_id=null

**Comment by alykhank** [comment]
The `null` parameter for any PATCH appears to always get string-escaped, we have to figure out how to actually clear fields via API request

**Comment by alykhank** [comment]
This was resolved on the client side by using "null" in the request body.
